name: Build macOS Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build macOS executable
      run: |
        pyinstaller --add-data "assets:assets" --icon="icono.icns" --windowed AquaBella.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AquaBella-macOS
        path: dist/AquaBella
